services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
      - "8080:8080"
    volumes:
      - ./app:/app 
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    command: ["npm", "run", "dev"]